using System;

public void foo()
{
    throw new Exception("foo");
}

void main()
{
    try
    {
        foo();
    }    
    catch (Exception ex)
    {
        Console.Error.WriteLine(ex.Message);
    }
}
